/** Whisperheads sample data for dev mode — from create-music/fixtures/whisperheads/ */
import type { AnnotatedLyrics, ConvergenceRound, PianoRollSpec } from "./types";

export const sampleSpec: PianoRollSpec = {
	bpm: 85,
	time_signature: "4/4",
	key: "D minor",
	total_bars: 8,
	sections: [
		{
			section_name: "verse",
			start_bar: 1,
			end_bar: 4,
			chord_progression: ["Dm", "Am", "Bb", "Gm"],
			energy_curve: [0.2, 0.25, 0.3, 0.35],
		},
		{
			section_name: "chorus",
			start_bar: 5,
			end_bar: 8,
			chord_progression: ["Bb", "F", "Gm", "Dm"],
			energy_curve: [0.6, 0.7, 0.8, 0.65],
		},
	],
	notes: [
		{ pitch: "D3", start_beat: 0, duration_beats: 4, velocity: 60, instrument: "bass" },
		{ pitch: "A2", start_beat: 4, duration_beats: 4, velocity: 60, instrument: "bass" },
		{ pitch: "Bb2", start_beat: 8, duration_beats: 4, velocity: 65, instrument: "bass" },
		{ pitch: "G2", start_beat: 12, duration_beats: 4, velocity: 65, instrument: "bass" },
		{ pitch: "D4", start_beat: 0, duration_beats: 2, velocity: 50, instrument: "keys" },
		{ pitch: "F4", start_beat: 2, duration_beats: 2, velocity: 50, instrument: "keys" },
		{ pitch: "A3", start_beat: 4, duration_beats: 2, velocity: 50, instrument: "keys" },
		{ pitch: "C4", start_beat: 6, duration_beats: 2, velocity: 50, instrument: "keys" },
		{ pitch: "Bb3", start_beat: 8, duration_beats: 2, velocity: 55, instrument: "keys" },
		{ pitch: "D4", start_beat: 10, duration_beats: 2, velocity: 55, instrument: "keys" },
		{ pitch: "G3", start_beat: 12, duration_beats: 2, velocity: 55, instrument: "keys" },
		{ pitch: "Bb3", start_beat: 14, duration_beats: 2, velocity: 55, instrument: "keys" },
		{ pitch: "Bb3", start_beat: 16, duration_beats: 4, velocity: 80, instrument: "bass" },
		{ pitch: "F3", start_beat: 20, duration_beats: 4, velocity: 80, instrument: "bass" },
		{ pitch: "G3", start_beat: 24, duration_beats: 4, velocity: 85, instrument: "bass" },
		{ pitch: "D3", start_beat: 28, duration_beats: 4, velocity: 75, instrument: "bass" },
		{ pitch: "D4", start_beat: 16, duration_beats: 1, velocity: 90, instrument: "vocal" },
		{ pitch: "D4", start_beat: 17, duration_beats: 1, velocity: 85, instrument: "vocal" },
		{ pitch: "D4", start_beat: 18.5, duration_beats: 1, velocity: 95, instrument: "vocal" },
		{ pitch: "C4", start_beat: 19.5, duration_beats: 0.5, velocity: 80, instrument: "vocal" },
		{ pitch: "D4", start_beat: 20, duration_beats: 3, velocity: 100, instrument: "vocal" },
	],
};

export const sampleLyrics: AnnotatedLyrics = {
	title: "Whisperheads",
	artist: "Horus",
	bpm: 85,
	time_signature: "4/4",
	key: "D minor",
	genre_tags: ["indie", "alternative", "atmospheric", "dark"],
	phrases: [
		{
			text: "They speak in static frequencies",
			section: "verse",
			bar: 1,
			beat: 1,
			duration_beats: 8,
			emotion: "fear",
			dynamics: "p",
			vocal_direction: "whisper",
			syllables: [
				{ text: "They", beat: 1, hold_beats: 0.5, stress: false },
				{ text: "speak", beat: 1.5, hold_beats: 1, stress: true },
				{ text: "in", beat: 2.5, hold_beats: 0.5, stress: false },
				{ text: "sta", beat: 3, hold_beats: 0.5, stress: true },
				{ text: "tic", beat: 3.5, hold_beats: 0.5, stress: false },
				{ text: "fre", beat: 5, hold_beats: 0.5, stress: true },
				{ text: "quen", beat: 5.5, hold_beats: 0.5, stress: false },
				{ text: "cies", beat: 6, hold_beats: 2, stress: false },
			],
		},
		{
			text: "Beneath the hum of broken light",
			section: "verse",
			bar: 3,
			beat: 1,
			duration_beats: 8,
			emotion: "sadness",
			dynamics: "mp",
			vocal_direction: "sing",
			syllables: [
				{ text: "Be", beat: 1, hold_beats: 0.5, stress: false },
				{ text: "neath", beat: 1.5, hold_beats: 1, stress: true },
				{ text: "the", beat: 2.5, hold_beats: 0.5, stress: false },
				{ text: "hum", beat: 3, hold_beats: 1, stress: true },
				{ text: "of", beat: 5, hold_beats: 0.5, stress: false },
				{ text: "bro", beat: 5.5, hold_beats: 0.5, stress: true },
				{ text: "ken", beat: 6, hold_beats: 0.5, stress: false },
				{ text: "light", beat: 6.5, hold_beats: 1.5, stress: true },
			],
		},
		{
			text: "We are the whisperheads",
			section: "chorus",
			bar: 5,
			beat: 1,
			duration_beats: 8,
			emotion: "trust",
			dynamics: "f",
			vocal_direction: "belt",
			syllables: [
				{ text: "We", beat: 1, hold_beats: 1, stress: true },
				{ text: "are", beat: 2, hold_beats: 1, stress: false },
				{ text: "the", beat: 3, hold_beats: 0.5, stress: false },
				{ text: "whis", beat: 3.5, hold_beats: 1, stress: true },
				{ text: "per", beat: 4.5, hold_beats: 0.5, stress: false },
				{ text: "heads", beat: 5, hold_beats: 3, stress: true },
			],
		},
		{
			text: "Tuned to the noise you left behind",
			section: "chorus",
			bar: 7,
			beat: 1,
			duration_beats: 8,
			emotion: "anger",
			dynamics: "f",
			vocal_direction: "belt",
			syllables: [
				{ text: "Tuned", beat: 1, hold_beats: 1, stress: true },
				{ text: "to", beat: 2, hold_beats: 0.5, stress: false },
				{ text: "the", beat: 2.5, hold_beats: 0.5, stress: false },
				{ text: "noise", beat: 3, hold_beats: 1.5, stress: true },
				{ text: "you", beat: 5, hold_beats: 0.5, stress: false },
				{ text: "left", beat: 5.5, hold_beats: 1, stress: true },
				{ text: "be", beat: 6.5, hold_beats: 0.5, stress: false },
				{ text: "hind", beat: 7, hold_beats: 1, stress: true },
			],
		},
	],
};

export const sampleRounds: ConvergenceRound[] = [
	{
		round: 1,
		timestamp: "2026-03-18T02:00:00Z",
		tempo_delta: 12.5,
		key_match: false,
		chord_accuracy: 0.25,
		dynamics_rmse: 0.45,
		timing_drift_ms: 180,
		aggregate: 0.82,
		converged: false,
	},
	{
		round: 2,
		timestamp: "2026-03-18T02:15:00Z",
		tempo_delta: 5.2,
		key_match: true,
		chord_accuracy: 0.5,
		dynamics_rmse: 0.3,
		timing_drift_ms: 95,
		aggregate: 0.48,
		converged: false,
	},
	{
		round: 3,
		timestamp: "2026-03-18T02:30:00Z",
		tempo_delta: 2.1,
		key_match: true,
		chord_accuracy: 0.75,
		dynamics_rmse: 0.18,
		timing_drift_ms: 42,
		aggregate: 0.22,
		converged: true,
	},
];
