# Generated by test-lab — blind adversarial evaluation
"""Integration tests for /chat and /chat/stream endpoints.

Uses httpx + TestClient with mocked subprocess output —
no running Docker container or real CLI backends needed.
"""
from __future__ import annotations

import asyncio
import base64
import json
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from httpx import ASGITransport, AsyncClient

from image_io import MIME_TO_EXT

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

# Minimal valid 1x1 red PNG (67 bytes)
TINY_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4"
    "2mP8/58BAwAI/AL+hc2rNAAAAABJRU5ErkJggg=="
)
TINY_PNG_BYTES = base64.b64decode(TINY_PNG_B64)

# Fake Claude stream-json output lines
CLAUDE_STREAM_LINES = [
    json.dumps({"type": "assistant", "message": {"content": [{"type": "text", "text": "Hello from mock"}]}}).encode() + b"\n",
    json.dumps({"type": "result", "result": "Hello from mock", "total_cost_usd": 0.01, "usage": {"input_tokens": 10, "output_tokens": 5}}).encode() + b"\n",
]


def _make_mock_process(stdout_lines: list[bytes], exit_code: int = 0):
    """Build a mock asyncio.subprocess.Process with canned stdout."""
    proc = AsyncMock()
    proc.returncode = exit_code
    proc.kill = MagicMock()

    line_iter = iter(stdout_lines + [b""])  # empty bytes = EOF

    async def readline():
        return next(line_iter, b"")

    proc.stdout = AsyncMock()
    proc.stdout.readline = readline

    # stderr — return empty
    async def read_stderr():
        return b""

    proc.stderr = AsyncMock()
    proc.stderr.read = read_stderr

    async def wait():
        pass

    proc.wait = wait
    return proc


@pytest.fixture
def backends_yml(tmp_path: Path):
    """Write a minimal backends.yml for testing."""
    yml = tmp_path / "backends.yml"
    yml.write_text(
        "backends:\n"
        "  claude:\n"
        "    cli: echo\n"
        '    prompt_flag: "-p"\n'
        "    output_flags: []\n"
        '    max_turns_flag: "--max-turns"\n'
        '    model_flag: "--model"\n'
        "    system_prompt_flag: null\n"
        "    image_flag: null\n"
        "    auth_dir: .claude\n"
        "    env_strip: []\n"
        "    default_model: sonnet\n"
        "    models:\n"
        '      - pattern: "sonnet*"\n'
        '      - pattern: "opus*"\n'
        '      - pattern: "claude-*"\n'
        "  gemini:\n"
        "    cli: echo\n"
        '    prompt_flag: "-p"\n'
        "    output_flags: []\n"
        "    max_turns_flag: null\n"
        '    model_flag: "--model"\n'
        "    system_prompt_flag: null\n"
        '    image_flag: "-f"\n'
        "    auth_dir: .gemini\n"
        "    env_strip: []\n"
        "    default_model: gemini-2.5-pro\n"
        "    models:\n"
        '      - pattern: "gemini-*"\n'
    )
    return yml


@pytest.fixture
def app_client(backends_yml, tmp_path):
    """Patch BACKENDS_FILE and return the FastAPI app for testing."""
    with patch("server.BACKENDS_FILE", backends_yml), \
         patch("server.WORKSPACE_DIR", None):
        import server
        # Force reload backends synchronously
        import yaml
        with open(backends_yml) as f:
            data = yaml.safe_load(f)
        server.BACKENDS = data.get("backends", {})
        server.MODEL_INDEX.clear()
        for bname, cfg in server.BACKENDS.items():
            for m in cfg.get("models", []):
                server.MODEL_INDEX.append((m["pattern"], bname))
        yield server.app


# ---------------------------------------------------------------------------
# /chat endpoint tests
# ---------------------------------------------------------------------------

class TestChatEndpoint:
    @pytest.mark.asyncio
    async def test_basic_chat(self, app_client):
        """POST /chat returns structured JSON with response text."""
        mock_proc = _make_mock_process(CLAUDE_STREAM_LINES, exit_code=0)

        with patch("server.asyncio.create_subprocess_exec", return_value=mock_proc):
            async with AsyncClient(transport=ASGITransport(app=app_client), base_url="http://test") as ac:
                resp = await ac.post("/chat", json={"prompt": "Say hello", "model": "sonnet"})

        assert resp.status_code == 200
        body = resp.json()
        assert body["response"] == "Hello from mock"
        assert body["backend"] == "claude"
        assert body["exit_code"] == 0
        assert body["duration_ms"] >= 0
        assert body["cost_usd"] == 0.01
        assert body["tokens_in"] == 10
        assert body["tokens_out"] == 5

    @pytest.mark.asyncio
    async def test_chat_with_input_images(self, app_client):
        """POST /chat with images writes temp files and passes to _build_cmd."""
        mock_proc = _make_mock_process(CLAUDE_STREAM_LINES, exit_code=0)

        with patch("server.asyncio.create_subprocess_exec", return_value=mock_proc) as mock_exec:
            async with AsyncClient(transport=ASGITransport(app=app_client), base_url="http://test") as ac:
                resp = await ac.post("/chat", json={
                    "prompt": "Review this screenshot",
                    "model": "sonnet",
                    "images": [{"data": TINY_PNG_B64, "media_type": "image/png", "filename": "shot.png"}],
                })

        assert resp.status_code == 200
        # Verify the command included the image reference in the prompt
        call_args = mock_exec.call_args
        cmd = call_args[0]  # positional args to create_subprocess_exec
        prompt_arg = cmd[2]  # after cli and -p
        assert "[Image:" in prompt_arg
        assert "shot.png" in prompt_arg

    @pytest.mark.asyncio
    async def test_chat_collects_output_images(self, app_client, tmp_path):
        """POST /chat collects images from the output directory."""
        mock_proc = _make_mock_process(CLAUDE_STREAM_LINES, exit_code=0)
        out_dir = tmp_path / "agent_output"
        out_dir.mkdir()
        # Pre-place an output image
        (out_dir / "result.png").write_bytes(TINY_PNG_BYTES)

        with patch("server.asyncio.create_subprocess_exec", return_value=mock_proc), \
             patch("server.tempfile.mkdtemp", side_effect=[str(out_dir)]):
            # Patch only the output tmpdir creation (skip img_tmpdir since no images)
            async with AsyncClient(transport=ASGITransport(app=app_client), base_url="http://test") as ac:
                resp = await ac.post("/chat", json={
                    "prompt": "Generate an image",
                    "model": "sonnet",
                    "output_dir": str(out_dir),
                })

        assert resp.status_code == 200
        body = resp.json()
        assert body["images"] is not None
        assert len(body["images"]) == 1
        assert body["images"][0]["filename"] == "result.png"
        assert body["images"][0]["media_type"] == "image/png"
        # Round-trip: data decodes back to original bytes
        assert base64.b64decode(body["images"][0]["data"]) == TINY_PNG_BYTES

    @pytest.mark.asyncio
    async def test_chat_with_gemini_image_flags(self, app_client):
        """Gemini backend gets -f flags for image attachments."""
        mock_proc = _make_mock_process([b"Gemini says hi\n"], exit_code=0)

        with patch("server.asyncio.create_subprocess_exec", return_value=mock_proc) as mock_exec:
            async with AsyncClient(transport=ASGITransport(app=app_client), base_url="http://test") as ac:
                resp = await ac.post("/chat", json={
                    "prompt": "Review screenshot",
                    "model": "gemini-2.5-pro",
                    "images": [{"data": TINY_PNG_B64, "media_type": "image/png"}],
                })

        assert resp.status_code == 200
        cmd = mock_exec.call_args[0]
        cmd_str = " ".join(str(c) for c in cmd)
        assert "-f" in cmd_str

    def test_build_cmd_disables_gemini_sandbox(self, app_client):
        """Gemini CLI must explicitly disable sandbox inside the Docker subagent."""
        import server

        server.BACKENDS = {
            "gemini": {
                "cli": "gemini",
                "prompt_flag": "-p",
                "output_flags": ["--sandbox", "false", "--yolo"],
                "max_turns_flag": None,
                "model_flag": "--model",
                "system_prompt_flag": None,
                "image_flag": "-f",
            }
        }

        cmd = server._build_cmd("gemini", "gemini-2.5-flash", "say hi")
        assert "--sandbox" in cmd
        assert "false" in cmd
        assert "--yolo" in cmd


# ---------------------------------------------------------------------------
# /chat/stream endpoint tests
# ---------------------------------------------------------------------------

class TestChatStreamEndpoint:
    @pytest.mark.asyncio
    async def test_basic_stream(self, app_client):
        """POST /chat/stream returns SSE events including meta, text/result, and done."""
        mock_proc = _make_mock_process(CLAUDE_STREAM_LINES, exit_code=0)

        with patch("server.asyncio.create_subprocess_exec", return_value=mock_proc):
            async with AsyncClient(transport=ASGITransport(app=app_client), base_url="http://test") as ac:
                resp = await ac.post("/chat/stream", json={"prompt": "Hello", "model": "sonnet"})

        assert resp.status_code == 200
        assert "text/event-stream" in resp.headers["content-type"]

        # Parse SSE events from body
        events = _parse_sse(resp.text)
        event_types = [e["event"] for e in events]

        assert "meta" in event_types
        assert "done" in event_types

        # Meta event has backend info
        meta = next(e for e in events if e["event"] == "meta")
        assert meta["data"]["backend"] == "claude"

        # Done event has exit_code
        done = next(e for e in events if e["event"] == "done")
        assert done["data"]["exit_code"] == 0

    @pytest.mark.asyncio
    async def test_stream_with_output_images(self, app_client, tmp_path):
        """POST /chat/stream emits an images event when output images exist."""
        mock_proc = _make_mock_process(CLAUDE_STREAM_LINES, exit_code=0)
        out_dir = tmp_path / "stream_output"
        out_dir.mkdir()
        (out_dir / "generated.png").write_bytes(TINY_PNG_BYTES)

        with patch("server.asyncio.create_subprocess_exec", return_value=mock_proc):
            async with AsyncClient(transport=ASGITransport(app=app_client), base_url="http://test") as ac:
                resp = await ac.post("/chat/stream", json={
                    "prompt": "Make an image",
                    "model": "sonnet",
                    "output_dir": str(out_dir),
                })

        events = _parse_sse(resp.text)
        event_types = [e["event"] for e in events]

        # images event must come before done
        assert "images" in event_types
        assert "done" in event_types
        img_idx = event_types.index("images")
        done_idx = event_types.index("done")
        assert img_idx < done_idx

        img_event = events[img_idx]
        assert img_event["data"]["count"] == 1
        assert img_event["data"]["images"][0]["filename"] == "generated.png"

    @pytest.mark.asyncio
    async def test_stream_no_images_when_empty(self, app_client, tmp_path):
        """POST /chat/stream does NOT emit images event when output dir is empty."""
        mock_proc = _make_mock_process(CLAUDE_STREAM_LINES, exit_code=0)
        out_dir = tmp_path / "empty_output"
        out_dir.mkdir()

        with patch("server.asyncio.create_subprocess_exec", return_value=mock_proc):
            async with AsyncClient(transport=ASGITransport(app=app_client), base_url="http://test") as ac:
                resp = await ac.post("/chat/stream", json={
                    "prompt": "No images expected",
                    "model": "sonnet",
                    "output_dir": str(out_dir),
                })

        events = _parse_sse(resp.text)
        event_types = [e["event"] for e in events]
        assert "images" not in event_types

    @pytest.mark.asyncio
    async def test_stream_with_input_images(self, app_client):
        """POST /chat/stream with input images wires them into the command."""
        mock_proc = _make_mock_process(CLAUDE_STREAM_LINES, exit_code=0)

        with patch("server.asyncio.create_subprocess_exec", return_value=mock_proc) as mock_exec:
            async with AsyncClient(transport=ASGITransport(app=app_client), base_url="http://test") as ac:
                resp = await ac.post("/chat/stream", json={
                    "prompt": "Review this",
                    "model": "sonnet",
                    "images": [{"data": TINY_PNG_B64, "media_type": "image/png"}],
                })

        assert resp.status_code == 200
        cmd = mock_exec.call_args[0]
        prompt_arg = cmd[2]
        assert "[Image:" in prompt_arg


# ---------------------------------------------------------------------------
# SSE parser
# ---------------------------------------------------------------------------

def _parse_sse(text: str) -> list[dict]:
    """Parse SSE text into list of {event, data} dicts."""
    events = []
    current_event = None
    current_data = None

    for line in text.split("\n"):
        if line.startswith("event: "):
            current_event = line[7:]
        elif line.startswith("data: "):
            current_data = line[6:]
        elif line == "" and current_event is not None and current_data is not None:
            try:
                data = json.loads(current_data)
            except json.JSONDecodeError:
                data = current_data
            events.append({"event": current_event, "data": data})
            current_event = None
            current_data = None

    return events
