# Generated by test-lab — blind adversarial evaluation
"""Tests for subagent-service image I/O helpers.

Exercises the full encode→decode→collect round-trip without a running server.
"""
from __future__ import annotations

import base64
import tempfile
from pathlib import Path

import pytest

from image_io import (
    ImageInput,
    OutputImage,
    build_image_flags,
    collect_output_images,
    inject_image_refs,
    write_input_images,
)
from parse_output import extract_usage_from_events, parse_tokens_from_stderr


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

# Minimal valid 1x1 red PNG (67 bytes)
TINY_PNG_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR4"
    "2mP8/58BAwAI/AL+hc2rNAAAAABJRU5ErkJggg=="
)
TINY_PNG_BYTES = base64.b64decode(TINY_PNG_B64)

# Minimal valid 1x1 white JPEG
TINY_JPEG_B64 = (
    "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsL"
    "DBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/"
    "2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy"
    "MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QA"
    "HwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUF"
    "BAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkK"
    "FhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1"
    "dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXG"
    "x8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEB"
    "AQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAEC"
    "AxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYI4Q/"
    "RFhHcmJzdXZxc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqy"
    "s7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/"
    "2gAMAwEAAhEDEQA/AP/Z"
)


@pytest.fixture
def work_dir():
    with tempfile.TemporaryDirectory(prefix="test_img_io_") as d:
        yield Path(d)


# ---------------------------------------------------------------------------
# write_input_images
# ---------------------------------------------------------------------------

class TestWriteInputImages:
    def test_single_png(self, work_dir: Path):
        images = [ImageInput(data=TINY_PNG_B64, media_type="image/png")]
        paths = write_input_images(images, work_dir)
        assert len(paths) == 1
        assert paths[0].exists()
        assert paths[0].suffix == ".png"
        assert paths[0].read_bytes() == TINY_PNG_BYTES

    def test_custom_filename(self, work_dir: Path):
        images = [ImageInput(data=TINY_PNG_B64, media_type="image/png", filename="screenshot.png")]
        paths = write_input_images(images, work_dir)
        assert paths[0].name == "screenshot.png"

    def test_multiple_images(self, work_dir: Path):
        images = [
            ImageInput(data=TINY_PNG_B64, media_type="image/png"),
            ImageInput(data=TINY_JPEG_B64, media_type="image/jpeg"),
        ]
        paths = write_input_images(images, work_dir)
        assert len(paths) == 2
        assert paths[0].suffix == ".png"
        assert paths[1].suffix == ".jpg"

    def test_sanitizes_filename(self, work_dir: Path):
        images = [ImageInput(data=TINY_PNG_B64, media_type="image/png", filename="bad/file name!.png")]
        paths = write_input_images(images, work_dir)
        # Should not contain slashes or special chars
        assert "/" not in paths[0].name
        assert "!" not in paths[0].name


# ---------------------------------------------------------------------------
# collect_output_images
# ---------------------------------------------------------------------------

class TestCollectOutputImages:
    def test_collects_png(self, work_dir: Path):
        # Write a PNG file into the output dir
        (work_dir / "result.png").write_bytes(TINY_PNG_BYTES)
        results = collect_output_images(work_dir)
        assert len(results) == 1
        assert results[0].media_type == "image/png"
        assert results[0].filename == "result.png"
        # Round-trip: decoded data matches original
        assert base64.b64decode(results[0].data) == TINY_PNG_BYTES

    def test_empty_dir(self, work_dir: Path):
        results = collect_output_images(work_dir)
        assert results == []

    def test_nonexistent_dir(self):
        results = collect_output_images(Path("/nonexistent/dir"))
        assert results == []

    def test_skips_large_files(self, work_dir: Path):
        # Create a >20MB file (should be skipped)
        big = work_dir / "huge.png"
        big.write_bytes(b"\x00" * (21 * 1024 * 1024))
        results = collect_output_images(work_dir)
        assert len(results) == 0

    def test_multiple_formats(self, work_dir: Path):
        (work_dir / "a.png").write_bytes(TINY_PNG_BYTES)
        (work_dir / "b.jpg").write_bytes(base64.b64decode(TINY_JPEG_B64))
        results = collect_output_images(work_dir)
        assert len(results) == 2
        filenames = {r.filename for r in results}
        assert "a.png" in filenames
        assert "b.jpg" in filenames


# ---------------------------------------------------------------------------
# Full round-trip: write → collect
# ---------------------------------------------------------------------------

class TestRoundTrip:
    def test_write_then_collect(self, work_dir: Path):
        """Simulates agent receiving images, writing them, then collecting output."""
        # Simulate input images being written
        input_images = [
            ImageInput(data=TINY_PNG_B64, media_type="image/png", filename="input.png"),
        ]
        input_dir = work_dir / "input"
        input_dir.mkdir()
        paths = write_input_images(input_images, input_dir)
        assert len(paths) == 1

        # Simulate agent producing output images
        output_dir = work_dir / "output"
        output_dir.mkdir()
        (output_dir / "generated.png").write_bytes(TINY_PNG_BYTES)

        # Collect output
        output_images = collect_output_images(output_dir)
        assert len(output_images) == 1
        assert output_images[0].filename == "generated.png"
        assert base64.b64decode(output_images[0].data) == TINY_PNG_BYTES


# ---------------------------------------------------------------------------
# inject_image_refs
# ---------------------------------------------------------------------------

class TestInjectImageRefs:
    def test_no_images(self):
        assert inject_image_refs("hello", []) == "hello"

    def test_single_image(self, work_dir: Path):
        p = work_dir / "test.png"
        result = inject_image_refs("Review this", [p])
        assert f"[Image: {p}]" in result
        assert result.endswith("Review this")

    def test_multiple_images(self, work_dir: Path):
        paths = [work_dir / "a.png", work_dir / "b.jpg"]
        result = inject_image_refs("prompt", paths)
        assert "[Image:" in result
        assert result.count("[Image:") == 2


# ---------------------------------------------------------------------------
# build_image_flags
# ---------------------------------------------------------------------------

class TestBuildImageFlags:
    def test_no_flag(self, work_dir: Path):
        paths = [work_dir / "a.png"]
        assert build_image_flags(None, paths) == []

    def test_gemini_flag(self, work_dir: Path):
        paths = [work_dir / "a.png", work_dir / "b.png"]
        flags = build_image_flags("-f", paths)
        assert flags == ["-f", str(paths[0]), "-f", str(paths[1])]

    def test_no_paths(self):
        assert build_image_flags("-f", []) == []


# ---------------------------------------------------------------------------
# parse_output helpers
# ---------------------------------------------------------------------------

class TestExtractUsageFromEvents:
    def test_result_event(self):
        events = [
            {"type": "text", "content": "hello"},
            {"type": "result", "total_cost_usd": 0.05, "usage": {"input_tokens": 100, "output_tokens": 50}},
        ]
        cost, t_in, t_out = extract_usage_from_events(events)
        assert cost == 0.05
        assert t_in == 100
        assert t_out == 50

    def test_no_result(self):
        cost, t_in, t_out = extract_usage_from_events([{"type": "text"}])
        assert cost is None
        assert t_in is None

    def test_empty(self):
        cost, t_in, t_out = extract_usage_from_events([])
        assert cost is None


class TestParseTokensFromStderr:
    def test_in_out_pattern(self):
        stderr = "Tokens: 1234 in / 567 out"
        t_in, t_out = parse_tokens_from_stderr(stderr)
        assert t_in == 1234
        assert t_out == 567

    def test_input_output_pattern(self):
        stderr = "input_tokens: 500\noutput_tokens: 200"
        t_in, t_out = parse_tokens_from_stderr(stderr)
        assert t_in == 500
        assert t_out == 200

    def test_no_tokens(self):
        t_in, t_out = parse_tokens_from_stderr("no token info here")
        assert t_in is None
        assert t_out is None
