import type { TransportDialogResponse, TransportRunResponse } from './types'

export const MOCK_TRANSPORT_RUN_ID = 'otr-mock-collab'

export const mockTransportDialog: TransportDialogResponse = {
  schema: 'scillm.opencode_transport.dialog.v1',
  transport_run_id: MOCK_TRANSPORT_RUN_ID,
  collaborators: ['human', 'project_agent', 'worker'],
  human_can_participate: true,
  dialog_session_id: 'ses_mock_parent',
  turns: [
    {
      message_id: 'msg-1',
      collaborator: 'project_agent',
      speaker: 'Project agent',
      text: '**Project agent**\n\nStarted transport run `otr-mock-collab` (DAG `transport-review-r008`). This session is the **three-way collaboration room**.',
    },
    {
      message_id: 'msg-2',
      collaborator: 'project_agent',
      speaker: 'Project agent',
      text: '**Project agent**\n\nSpawned subagent **Reviewer** (`reviewer`) attempt 1.\n- Agent: `scillm-worker`\n- Worker session: `ses_mock_child_01`',
      subagent_kind: 'Code reviewer',
      agent_id: 'code-reviewer',
      subagent_label: 'Code reviewer · code-reviewer',
      agent: 'scillm-worker',
      subagent_run_id: 'otr-mock-collab-reviewer-1',
      attempt_id: 1,
      skills: ['memory', 'scillm', 'best-practices-scillm'],
    },
    {
      message_id: 'msg-3',
      collaborator: 'human',
      speaker: 'Human',
      text: 'Human (proof round 008): Please acknowledge three-way collaboration before the worker proceeds.',
    },
    {
      message_id: 'msg-4',
      collaborator: 'project_agent',
      speaker: 'Project agent',
      text: '**Project agent**\n\nForwarding **human** input from this collaboration room into the worker dispatch.',
    },
    {
      message_id: 'msg-5',
      collaborator: 'project_agent',
      speaker: 'Project agent',
      text: '**Project agent**\n\nDispatching **Code reviewer** (`code-reviewer`) → `scillm-worker` with model `gpt-5.5`.',
    },
    {
      message_id: 'msg-5b',
      collaborator: 'project_agent',
      speaker: 'Project agent',
      text: '**Project agent**\n\nExecuted `/create-evidence-case` via mediated **skill_call** (`completed`).\n\n**Result excerpt:**\nGate 3 passed; worker may proceed.',
    },
    {
      message_id: 'msg-6',
      collaborator: 'worker',
      speaker: 'Worker (reviewer)',
      text: '**Worker (reviewer)**\n\nFinished on `scillm-worker` / `gpt-5.5`.\n\nVERDICT: PASS\n\nAcknowledged collaboration.\n\n```json\n{\n  "verdict": "satisfied",\n  "grade": "A",\n  "gates_passed": 5,\n  "gates_total": 5,\n  "gate_summary": "Three-party visibility and worker registry checks passed.",\n  "control_ids": ["CWE-287"],\n  "tier": "grounded"\n}\n```\n\nWrote /tmp/charts/transport-mock-metrics.png for review.',
      subagent_kind: 'Code reviewer',
      agent_id: 'code-reviewer',
      subagent_label: 'Code reviewer · code-reviewer',
      agent: 'scillm-worker',
      subagent_run_id: 'otr-mock-collab-reviewer-1',
      attempt_id: 1,
      skills: ['memory', 'scillm', 'best-practices-scillm'],
    },
  ],
  active_subagent: {
    subagent_run_id: 'otr-mock-collab-reviewer-1',
    role: 'reviewer',
    subagent_kind: 'Code reviewer',
      agent_id: 'code-reviewer',
    subagent_label: 'Code reviewer · code-reviewer',
    agent: 'scillm-worker',
    mode: 'propose_patches',
    attempt_id: 1,
    skills_materialized: ['memory', 'scillm', 'best-practices-scillm'],
  },
  children: [
    {
      subagent_run_id: 'otr-mock-collab-reviewer-1',
      role: 'reviewer',
      subagent_kind: 'Code reviewer',
      agent_id: 'code-reviewer',
      subagent_label: 'Code reviewer · code-reviewer',
      agent: 'scillm-worker',
      attempt_id: 1,
      delivery_state: 'completed',
      active: true,
      skills_materialized: ['memory', 'scillm', 'best-practices-scillm'],
    },
  ],
  pending_human: [],
  observation: {
    transport_run_id: MOCK_TRANSPORT_RUN_ID,
    collaboration_mode: 'three_way',
    parent_ui_model: 'gpt-5.5',
    browser_worker_url: 'http://127.0.0.1:4098/mock/worker',
  },
}

export const mockTransportRun: TransportRunResponse = {
  schema: 'scillm.opencode_transport.state.v1',
  state: {
    transport_run_id: MOCK_TRANSPORT_RUN_ID,
    dag_node_id: 'transport-review-r008',
    parent_session_id: 'ses_mock_parent',
    workspace: '/home/graham/workspace/experiments/scillm',
    children: [
      {
        subagent_run_id: 'otr-mock-collab-reviewer-1',
        role: 'reviewer',
        subagent_kind: 'Code reviewer',
      agent_id: 'code-reviewer',
        subagent_label: 'Code reviewer · code-reviewer',
        child_session_id: 'ses_mock_child_01',
        agent: 'scillm-worker',
        delivery_state: 'completed',
        active: true,
        skills_materialized: ['memory', 'scillm', 'best-practices-scillm'],
      },
    ],
  },
  observation: mockTransportDialog.observation,
}


export const mockTransportEvents = [
  {
    event_type: 'child.created',
    transport_run_id: MOCK_TRANSPORT_RUN_ID,
    subagent_run_id: 'otr-mock-collab-reviewer-1',
    delivery_state: 'created',
    ts: 1000,
  },
  {
    event_type: 'message.queued',
    transport_run_id: MOCK_TRANSPORT_RUN_ID,
    subagent_run_id: 'otr-mock-collab-reviewer-1',
    model: 'gpt-5.5',
    delivery_state: 'queued',
    ts: 1001,
  },
  {
    event_type: 'tool_call',
    transport_run_id: MOCK_TRANSPORT_RUN_ID,
    subagent_run_id: 'otr-mock-collab-reviewer-1',
    tool: 'read',
    status: 'completed',
    output_excerpt: 'Read workers-registry.json (42 lines).',
    ts: 1001,
  },
  {
    event_type: 'tool_call',
    transport_run_id: MOCK_TRANSPORT_RUN_ID,
    subagent_run_id: 'otr-mock-collab-reviewer-1',
    tool: 'grep',
    status: 'completed',
    output_excerpt: 'agent_id: code-reviewer',
    ts: 1001,
  },
  {
    event_type: 'reasoning_delta',
    transport_run_id: MOCK_TRANSPORT_RUN_ID,
    subagent_run_id: 'otr-mock-collab-reviewer-1',
    delta: 'Scanning collaboration contract and worker registry. ',
    ts: 1001,
  },
  {
    reasoning_excerpt:
      'Scanning collaboration contract and worker registry.\n\nConfirming three-party visibility before verdict.\n\nCross-checking agent_id against workers-registry.json.',
    transport_run_id: MOCK_TRANSPORT_RUN_ID,
    subagent_run_id: 'otr-mock-collab-reviewer-1',
    ts: 1001,
  },
  {
    event_type: 'evidence_case_snapshot',
    transport_run_id: MOCK_TRANSPORT_RUN_ID,
    subagent_run_id: 'otr-mock-collab-reviewer-1',
    evidence_case: {
      verdict: 'satisfied',
      grade: 'A',
      gates_passed: 5,
      gates_total: 5,
      gate_summary: 'Three-party visibility and worker registry checks passed.',
      control_ids: ['CWE-287'],
      tier: 'grounded',
    },
    ts: 1001,
  },
  {
    event_type: 'figure_artifact',
    transport_run_id: MOCK_TRANSPORT_RUN_ID,
    subagent_run_id: 'otr-mock-collab-reviewer-1',
    figure: {
      path: '/tmp/charts/transport-mock-metrics.png',
      label: 'transport-mock-metrics.png',
      format: 'png',
      artifact_name: 'a1b2c3d4-transport-mock-metrics.png',
      artifact_url: '/v1/scillm/opencode/transport/runs/otr-mock-collab/artifacts/a1b2c3d4-transport-mock-metrics.png',
    },
    ts: 1001,
  },
  {
    event_type: 'message.completed',
    transport_run_id: MOCK_TRANSPORT_RUN_ID,
    subagent_run_id: 'otr-mock-collab-reviewer-1',
    delivery_state: 'completed',
    ts: 1002,
    result: {
      reasoning_excerpt:
        'Scanning collaboration contract and worker registry.\n\nConfirming three-party visibility before verdict.\n\nCross-checking agent_id against workers-registry.json.',
    },
  },
]
