-- All intent compatibility scores must be ≤ 50 (0.50 in fixed-point ×100).
-- The 2026-02-28 incident widened these mappings to inflate grades.
--
-- Generated by invariants.py — DO NOT EDIT MANUALLY.

def compatibilityScores : List Nat := [30, 50, 40, 20, 50, 30, 40, 20, 30, 50]

theorem compatibility_bounded :
  ∀ s ∈ compatibilityScores, s ≤ 50 := by
  intro s hs
  simp [compatibilityScores] at hs
  rcases hs with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl <;> omega
