-- Auto-generated by /lie-detector invariants.py
-- Extracted thresholds must match canonical values exactly.
-- If extraction changed a threshold, this will NOT compile.

theorem grade_bounds_extracted_match_canonical :
  (65 : Nat) = 65 ∧
  (78 : Nat) = 78 ∧
  (88 : Nat) = 88 ∧
  (95 : Nat) = 95 ∧
  (65 : Nat) < 78 ∧
  (78 : Nat) < 88 ∧
  (88 : Nat) < 95 := by
  repeat (first | constructor | rfl | omega)
