-- Auto-generated by /lie-detector invariants.py
-- Extracted dimension weights must sum to 100.
-- Values: 22 + 18 + 16 + 14 + 12 + 10 + 8

theorem weights_extracted_sum :
  (22 + 18 + 16 + 14 + 12 + 10 + 8 : Nat) = 100 := by omega
