/**
 * Centralized agent identity registry.
 *
 * Loads .pi/agents-registry.json (generated by agents-registry skill)
 * or falls back to filesystem scan of .pi/agents/ directories.
 */

import * as fs from "fs";
import * as path from "path";
import { parseFrontmatter } from "../utils/frontmatter.js";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface AgentCollaborator {
	id: string;
	role: string;
}

export interface AgentEntry {
	id: string;
	name: string;
	scope: string;
	provides: string[];
	composes: string[];
	collaborators: AgentCollaborator[];
	taxonomy_bridges: string[];
	voice: { enabled: boolean; voice_id?: string };
	inference: { preferred_model?: string };
	paths: { agents_md: string };
	active: boolean;
}

export interface AgentRegistryData {
	version: number;
	generated_by: string;
	agent_count: number;
	agents: AgentEntry[];
}

// ─── Registry ─────────────────────────────────────────────────────────────────

export class AgentRegistry {
	private agents: Map<string, AgentEntry> = new Map();
	private capabilityIndex: Map<string, string[]> = new Map();
	private loaded = false;

	constructor(private registryPath?: string) {}

	/**
	 * Ensure registry is loaded (lazy init).
	 */
	private ensureLoaded(): void {
		if (this.loaded) return;
		this.load();
	}

	/**
	 * Load from JSON file or fall back to filesystem scan.
	 */
	load(registryPath?: string): void {
		const jsonPath = registryPath ?? this.registryPath ?? this.findRegistryJson();

		if (jsonPath && fs.existsSync(jsonPath)) {
			this.loadFromJson(jsonPath);
		} else {
			this.loadFromFilesystem();
		}
		this.buildCapabilityIndex();
		this.loaded = true;
	}

	private findRegistryJson(): string | null {
		let dir = process.cwd();
		while (true) {
			const candidate = path.join(dir, ".pi", "agents-registry.json");
			if (fs.existsSync(candidate)) return candidate;
			const parent = path.dirname(dir);
			if (parent === dir) return null;
			dir = parent;
		}
	}

	private loadFromJson(jsonPath: string): void {
		const data: AgentRegistryData = JSON.parse(fs.readFileSync(jsonPath, "utf-8"));
		for (const agent of data.agents) {
			this.agents.set(agent.id, agent);
		}
	}

	private loadFromFilesystem(): void {
		let dir = process.cwd();
		while (true) {
			const agentsDir = path.join(dir, ".pi", "agents");
			if (fs.existsSync(agentsDir) && fs.statSync(agentsDir).isDirectory()) {
				for (const entry of fs.readdirSync(agentsDir)) {
					const mdPath = path.join(agentsDir, entry, "AGENTS.md");
					if (!fs.existsSync(mdPath)) continue;

					const content = fs.readFileSync(mdPath, "utf-8");
					const { frontmatter } = parseFrontmatter<Record<string, unknown>>(content);

					const name = (frontmatter.name as string) ?? entry;
					const collaboratorsRaw = (frontmatter.collaborators as string[]) ?? [];
					const collaborators: AgentCollaborator[] = collaboratorsRaw.map((c) => ({
						id: String(c).split("#")[0].trim(),
						role: "peer",
					}));

					const agent: AgentEntry = {
						id: name,
						name,
						scope: (frontmatter.scope as string) ?? name.replace(/-/g, "_"),
						provides: (frontmatter.provides as string[]) ?? [],
						composes: (frontmatter.composes as string[]) ?? [],
						collaborators,
						taxonomy_bridges: (frontmatter.taxonomy as string[]) ?? [],
						voice: { enabled: false },
						inference: {},
						paths: { agents_md: path.relative(process.cwd(), mdPath) },
						active: true,
					};
					this.agents.set(agent.id, agent);
				}
				break;
			}
			const parent = path.dirname(dir);
			if (parent === dir) break;
			dir = parent;
		}
	}

	private buildCapabilityIndex(): void {
		this.capabilityIndex.clear();
		for (const agent of this.agents.values()) {
			for (const cap of agent.provides) {
				const existing = this.capabilityIndex.get(cap) ?? [];
				existing.push(agent.id);
				this.capabilityIndex.set(cap, existing);
			}
		}
	}

	// ─── Public API ──────────────────────────────────────────────────────────

	listAll(): AgentEntry[] {
		this.ensureLoaded();
		return Array.from(this.agents.values());
	}

	getById(id: string): AgentEntry | undefined {
		this.ensureLoaded();
		return this.agents.get(id);
	}

	findByCapability(capability: string): AgentEntry[] {
		this.ensureLoaded();
		const ids = this.capabilityIndex.get(capability) ?? [];
		return ids.map((id) => this.agents.get(id)).filter(Boolean) as AgentEntry[];
	}

	getCollaborators(id: string): AgentEntry[] {
		this.ensureLoaded();
		const agent = this.agents.get(id);
		if (!agent) return [];
		return agent.collaborators.map((c) => this.agents.get(c.id)).filter(Boolean) as AgentEntry[];
	}

	getComposedSkills(id: string): string[] {
		this.ensureLoaded();
		const agent = this.agents.get(id);
		return agent?.composes ?? [];
	}

	/**
	 * Search agents by text match against name, scope, provides, and composes.
	 */
	search(query: string): AgentEntry[] {
		this.ensureLoaded();
		const q = query.toLowerCase();
		return Array.from(this.agents.values()).filter((a) => {
			return (
				a.name.includes(q) ||
				a.scope.includes(q) ||
				a.provides.some((p) => p.includes(q)) ||
				a.composes.some((c) => c.includes(q))
			);
		});
	}
}

// Singleton for shared use
let defaultRegistry: AgentRegistry | null = null;

export function getAgentRegistry(): AgentRegistry {
	if (!defaultRegistry) {
		defaultRegistry = new AgentRegistry();
	}
	return defaultRegistry;
}
